### ISSUE TITLE
Feature Request: Support Other Underlying Shells

### ISSUE THREAD

**Issue by C-Loftus** [paul-schaaf/vshell#1]
https://github.com/paul-schaaf/vshell/blob/c2d10d5d21ccd3fe032f1902cee0be74febafedd/src/update.rs#L261 

 I think it would be relatively easy to support other shells and would be really useful as it would give us access to things like environment variables and alises.  I'm pretty sure all that needs to be done in order to support this would be to have some sort of command line argument to take in the binary path of a shell.  I'm not super familiar with the codebase but I'm pretty sure that the shell path could then just be substituted for 'sh' in the code  referenced above

**Comment by paul-schaaf** [comment]
this was some code I forgot to update. what the shell is intended to do is to call the commands directly instead of delegating them to "sh" or any other shell. this is fixed in the newest commit

**Comment by C-Loftus** [comment]
Doesn't that still have the issue of not allowing shell built-ins, proper PATH, or customization? Although perhaps I'm misinterpreting what you mean by calling them directly. I wasn't sure if that was your goal or if this is a feasible feature.

Wouldn't it be easiest to simply pass the string the user has manipulated directly to a user specified shell and then keep a history of the standard output, as is done currently? Am I misinterpreting something about how this would be designed, since it seems easier and then you don't have to deal with re-implementing built-ins like cd or expanding ~, as I think is being done right now.

**Comment by paul-schaaf** [comment]
> Doesn't that still have the issue of not allowing shell built-ins, proper PATH, or customization?

yes. my plan was to implement all this myself

I agree that it would be quite nice to be able to use existing configuration. the reason I went away from simply delegating to a different shell is that some things seem difficult to implement without a custom shell. lets take ssh for example. for ssh to work with delegating Id need to keep the underlying shell alive instead of sending one-off commands to it. thats fine I can do that with Command::spawn. so I send commands to the child shell's stdin but how do I know when they are complete? I can read the childs stdout/stderr but that doesnt tell me when the child process of the child itself has completed which is a problem if I want to display the output of each command separately as i currently do. the child shell of course knows when its child has completed so I could add sth like `; echo VSHELL_COMMAND_END` to every call I make from vshell to its child shell which might work but also starts making me uncomfortable because while I cant think of any situations where it might go wrong, this certainly feels like something that could go wrong. maybe there is a better way to do this for ssh and other commands and I havent found it yet

**Comment by C-Loftus** [comment]
Ok interesting yes that makes sense I hadn't thought of ssh. I do worry a bit that it might be a significant development burden to essentially build a shell from the ground up. I wonder if perhaps it would be best to have a separate mode or something analogous for ssh specifically or other instances in which you need to keep the underlying shell alive.  So definitely not negate the great work you have done, but at least provide something naive as another option.

Although perhaps I am biased. I would be interested to hear other opinions on this. I honestly don't know how attached people are to their shell configs within the talon community. (ie I am thinking some people might have lots of natural language alises for better recognition but I could be totally wrong)

**Comment by paul-schaaf** [comment]
> I wonder if perhaps it would be best to have a separate mode or something analogous for ssh specifically or other instances in which you need to keep the underlying shell alive

yes perhaps. but perhaps if I do that the easier option is to just build it myself. i honestly dont know. right now I lean towards doing it myself, if only for the reason that I want to try it out

as far as development effort goes, Im ok with implementing everything myself cause I know I will use it. I think I can replicate most things rather easily except the commands that create a gui like `htop` but that would not be something I intend to be started from vshell (at least not until I have more important things for myself done). for now, I intend to replicate the common functionality that prints to stdout.

aliases is something I consider supporting although personally I have my aliases defined in talon files for easy portability.

> features many users may have grown accustomed to

is there anything particular you are thinking about?

**Comment by C-Loftus** [comment]
> the easier option is to just build it myself.
 Wouldn't it be quite easy to have a setting to just pass the arbitrary string edited within the TUI to the user defined shell?  I don't think these two options have to be mutually exclusive either.  But by all means if I am overlooking something and naively oversimplifying this please let me know.   I think it is a cool idea to have a shell specifically built for voice commands, I just think having the other option would be great too.

 Although as I have been thinking with ssh, couldn't you just ssh into the server, build vshell remotely, then run vshell in that server with their system shell?  and then you wouldn't have to worry about ssh'ing within vshell itself?  although maybe I'm overlooking something

For me at least I use a lot of helper functions in the shell that are tricky to put in Talon files.  I just feel like out of principle it might make things confusing for people to have a different syntax in vshell vs their system shell. (ie fish uses `set` for variables but I imagine you will not).  The syntax for command substitution or special things like getting the last index in array also varies quite a bit between shells,  if that is something you will implement.  I think implementing those qol features might start to get rather nasty

**Comment by paul-schaaf** [comment]
> Wouldn't it be quite easy to have a setting to just pass the arbitrary string edited within the TUI to the user defined shell?

oh I see, yes for one-off commands should be no problem. i can add that now already (you can technically already do this since shells usually have a cli option to pass the command as a string e.g. `bash/zsh -c "my command"` but having it as a separate command means you dont need any escaping which is better)! it just doesnt really work for flows where you have multiple commands that save states in variables because this would spawn a new child shell instance every time. if you want to keep state you have to keep the child shell alive but as I explained above Idk of a great way to separate command outputs then

> Although as I have been thinking with ssh, couldn't you just ssh into the server, build vshell remotely, then run vshell in that server with their system shell?

yes you could but if youre working with a lot of different and new servers spinning up and down where you have to always first install vshell I think it's better ux to have vshell be able to do that itself. also maybe you dont have organisational permissions to install it on the server youre sshing into

> For me at least I use a lot of helper functions in the shell that are tricky to put in Talon files.

are these public? Im very curious!

**Comment by C-Loftus** [comment]
Yeah, that makes sense. Honestly, for now, one-off commands are probably perfectly sufficient. Yeah, I was thinking about the `-c` flag as well but thought it might get rather tedious for users to have to specify that for every command.

That's fair with SSH. I typically only SSH into my own servers, so I have a bit of a biased perspective.

No, they aren't public. They aren't Talon specific, but are more so ways of just decreasing the verbosity of commands. For example, the following allows me to automatically create a directory if I am touching a file. This is not a major thing whatsoever, but just thought I would bring it up.

```
function touch
  set dir (dirname $argv)
  set file_name (basename $argv)
  mkdir -p $dir; /usr/bin/touch $argv

end
```

**Comment by paul-schaaf** [comment]
ive added the `se:<shell>` command which lets you execute a command in a shell of your choice. but it looks like functions dont work unless you preface the command with `source <.rc file> &&` . Ill add that to the command itself tomorrow so you dont have to type it. aliases also do not work at all for me even when sourcing.

**Comment by paul-schaaf** [comment]
are functions and alias not working unless you source - and then only functions work - happening for you as well @C-Loftus ?

**Comment by paul-schaaf** [comment]
only seems to be a problem with bash and zsh though. works with fish
